### ISSUE TITLE
Possibility to use vim instead of nano

### ISSUE THREAD

**Issue by kindkitchen** [cheesits456/bash-wtf#1]
# This is the most important package on my computer. So I need very often update its config file. And because I can't exit nano (because I spent my life to learn how exit vim) I hope dear developers will update this repository to have possibility use vim.

**Comment by cheesits456** [comment]
The program will now respect your `$EDITOR` environment variable

**Comment by cheesits456** [comment]
I've been trying to come up with more lines to add to the config file, any chance you could provide a PR with some of yours?
